### ISSUE TITLE
[Improvement] Specify a cache validator for minified assets + Support of 304 Not Modified header

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#10]
- Pingdom Tools throws the following error:

> The following resources are missing a cache validator. Resources that do not specify a cache validator cannot be refreshed efficiently. Specify a Last-Modified or ETag header to enable cache validation for the following resources:
> /min/xxxxx.js
> /min/xxxxx.js
> /min/css_async.js
> /min/xxxxx.css

- It would be useful to support 304 Not Modified headers to indicate when a file has not been modified

**Comment by hailite** [comment]
noted

**Comment by hailite** [comment]
Etag is automatically added by server if there is a cache ttl header, which means, currently it should work. Check http://34.224.235.132/ you will find it works.

Is your server latest lsws build?

**Comment by JMCA2** [comment]
I'm using LSWS 5.2

**Comment by hailite** [comment]
You need to check server setting to make sure Etag isn't turned off. As chatted in slack, I assume this is not issue related to plugin.
