### ISSUE TITLE
[Feature Request] Minify inline CSS/JS

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#11]
Just like with .css/.js files

**Comment by hailite** [comment]
Noted. Thanks.

**Comment by JMCA2** [comment]
@hailite Hi!
Any updates regarding this improvement? Any estimate on roadmap would be really appreciated. Maybe we expect this before the end of the year? It's the only issue preventing from using LSCWP as one-in-all minification plugin.
Thank you

**Comment by hailite** [comment]
Not an ETA yet. Have some other priority in dev plan still.

This is in our plan tho. Will update here once its done.

**Comment by JMCA2** [comment]
Ok thanks for the update. Appreciated

**Comment by hailite** [comment]
Done in https://github.com/litespeedtech/lscache_wp/commit/16c3fbaf4fe40c38d3b3efc8b8bc55ac083121f5

Please test the latest commit

**Comment by JMCA2** [comment]
Working great so far 👍
