### ISSUE TITLE
[Fix] Incessant Backtrace Warning in Debug.log

### ISSUE THREAD

**Issue by DaveyJake** [litespeedtech/lscache_wp#130]
I'm running `PHP 7.2` and inside my `debug.log` I am seeing the following warning countless times:

`
Backtrace from warning 'Invalid argument supplied for foreach()' at /my/path/to/wp-content/plugins/litespeed-cache/inc/utility.class.php 330
`

https://github.com/litespeedtech/lscache_wp/blob/0448b72bd688b8089871701fd7f82b1c13a7c27d/litespeed-cache/inc/utility.class.php#L330

To fix it, I've added the array `typecast` to the `$haystack` parameter:

```php
foreach ( (array) $haystack as $item ) { . . . }
```

The warning messages have now stopped.  Just wanted to make you all aware.  Keep up the great work!

**Comment by hailite** [comment]
Thanks for the feedback. We will test this in next release and make sure it won't happen.

**Comment by DaveyJake** [comment]
Fix was included as part of #131.
