### ISSUE TITLE
[Bug] Minification fails with line breaks before doctype

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#14]
As talked over Slack, minification fails when line breaks are present before the doctype declaration.

From debug logs:

```
Footer check failed: 2-
<!DOCTYPE html>
Optimizer bypass: Not frontend HTML type
```

**Comment by hailite** [comment]
In v1.3.1 it has been fixed. Do you still have this issue?

**Comment by JMCA2** [comment]
I didn't notice the improvement on the changelog for the update, thanks!
