### ISSUE TITLE
JQuery rewrite

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#144]
The latest version rewrites the JQuery links with a wrong URL.

Example:

- Original: https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js

- Using LS advanced features: https://ajax.googleapis.com/ajax/libs/jquery/1.12.4-wp/jquery.min.js

The issue disappears once LS settings are reset.
Tested on WP 5.2.1.

Attached settings .data file
[tmp.zip](https://github.com/litespeedtech/lscache_wp/files/3208783/tmp.zip)

**Comment by hailite** [comment]
Thanks for ur report. This issue is already fixed in https://github.com/litespeedtech/lscache_wp/commit/5f648b47da8624975c4671adf6665d135d57b3de and will be included in v2.9.8
