### ISSUE TITLE
[Feature Request] Load jQuery library from Google CDN

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#16]
It would be great to have the ability to replace the local WordPress installation jQuery with the Google CDN jQuery URL.

Most users have this already cached, and therefore reduces the amount of data to be downloaded. It would also make the combined .js file smaller.

Similar to what this plugin does: https://wordpress.org/plugins/use-google-libraries/ even if its just for jQuery, as it is the most commonly used library.

Might be helpful: https://www.wptutor.io/web/js/jquery-google-cdn

**Comment by hailite** [comment]
Noted. Will add.

**Comment by hailite** [comment]
9b72f0f3c08ba79e8cf2be8850178824832e37a4
