### ISSUE TITLE
[Improvement] Ability to exclude file from JS deferring

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#17]
Just like the JS Excludes options allows to opt-out certain scripts from minification/combination, it should also allow to exclude certain JS scripts from deferring.

This would be useful to solve console errors like:
`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

**Comment by hailite** [comment]
Noted. Will add in next release.

**Comment by JMCA2** [comment]
Seems fixed in b3d7725683d4fdfa30f049948a209b93ec7a8c6d.
