### ISSUE TITLE
Clear OPcache to ignore an error message

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#170]
Clear the PHP OPcache just after you write the new content to advanced-cache.php file so the users don't get the well-known error message because Litespeed cannot detect the newer PHP code.

https://www.php.net/manual/en/function.opcache-reset.php

**Comment by closte** [comment]
https://www.php.net/manual/en/function.opcache-get-status.php
Returns an array of information, optionally containing script specific state information, or FALSE on failure.

**Comment by hailite** [comment]
The improvement is included in https://github.com/litespeedtech/lscache_wp/commit/a50678f1ffff9cfc794594db5d09a485516a4c5d

Thanks.
