### ISSUE TITLE
Remove anti 304 headers

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#18]
I see more and more WordPress sites include headers preventing browser to receive 304 response.
Im not sure for what use case they send Pragma: no-cache header but it`s nice to have an option like "force remove Pragma header" or other headers that prevent 304 response especially on cacheable requests. 

I don`t see any use-case why cacheable request must have Pragma: no-cache header.

I`m not much into HTTP request headers, but the main point is to force 304 response on revisiting the same cached page with E-tag.

What do you think?

**Comment by hailite** [comment]
You mean remove `Cache-Control:no-cache, must-revalidate, max-age=0`?

**Comment by closte** [comment]
Yeah, I think those headers prevent 304 responses to work.

**Comment by hailite** [comment]
304 happens even there is `cache-control:no-cache` header ( you may have `disable cache` ticked in dev tools which disabled 304 ) :

**General**
Request URL:http://192.168.0.54/
Request Method:GET
Status Code:304 Not Modified
Remote Address:192.168.0.54:80
Referrer Policy:no-referrer-when-downgrade
Response Headers

**Response Headers:**
Accept-Ranges:bytes
Cache-Control:no-cache, must-revalidate, max-age=0
Connection:Keep-Alive
Content-Type:text/html; charset=UTF-8
Date:Thu, 19 Oct 2017 11:56:53 GMT
Etag:"7184-1508414210;gz"
Expires:Wed, 11 Jan 1984 05:00:00 GMT
Link:<http://192.168.0.54/wp-json/>; rel="https://api.w.org/"
Link:<http://192.168.0.54/>; rel=shortlink
Link:</min/76029.css>; rel=preload; as=style,</min/05ca1.js>; rel=preload; as=script,</min/css_async.js>; rel=preload; as=script
Server:LiteSpeed
X-LiteSpeed-Cache:hit,private
X-Powered-By:PHP/5.6.30

**Comment by closte** [comment]
The browser is not sending "if-none-match" and I think that is because the response had "cache-control:no-store, no-cache, must-revalidate".

I confirmed this in my Chrome and also found similar issue https://stackoverflow.com/questions/15900548/why-browser-does-not-send-if-none-match-header

**Comment by closte** [comment]
Removing two headers fix this issue.

`
Header unset Pragma
Header unset Cache-Control
`

**Comment by hailite** [comment]
You can manually try this first:
Edit `litespeed-cache/inc/litespeed-cache.class.php`, before line 445 `$this->_check_is_html( $buffer ) ;`, add a new line `header_remove('Pragma');header_remove('Cache-Control');` and purge all. See if it can work. On my side, its already 304 even i didn't add these codes.

**Comment by closte** [comment]
You are receiving 304 because you do not have "no-store" value in "cache-control" header. 
So my point is to remove the headers/values that prevent 304 to works.

I already make our plugin to check and remove these headers, but it`s good if native LSWP do the same.

**Comment by hailite** [comment]
Can you share the snippet of that logic in your code?

If I follow you correctly, you detect if there is `no-store` in `cache-control` or not. If yes, you will run `header_remove('Pragma');header_remove('Cache-Control');` ?

**Comment by closte** [comment]
I dont really parse/remove the `no-store` value, simple I replace the header with `no-cache, must-revalidate, max-age=0`

That is how it should work as I don`t see any other use case for a cacheable page.

1) Do not use local cache
2) Check if server has new version
3) Get 200 on new or 304 on not modified cache entity

The backend logic should be:

1) If a page is cacheable then on `template_redirect` action remove the headers.

```
header("Cache-Control:no-cache, must-revalidate, max-age=0");
header_remove("pragma");
```	

What do you think?

**Comment by hailite** [comment]
wordpress doesn't send `no-store` header. You may need to do a search in your instance to see which plugin made that header first.

**Comment by hailite** [comment]
I will mark this as won't do for now. If you get any new idea, please don't hesitate to let us know. 

Thanks.
