### ISSUE TITLE
Generate Key not possible

### ISSUE THREAD

**Issue by LarsK1** [litespeedtech/lscache_wp#188]
Hello,
every time I try to generate a key I get a page is not accessible error from the following url (https://apidev.quic.cloud/d/req_key?data=eyJoYXNoIjoidzEwd1IzZkZOdjBicmVTeiIsInNpdGVfdXJsIjoiaHR0cHM6XC9cL2xhcnMta3VzY2guZGUiLCJlbWFpbCI6ImxhcnNAbGFycy1rdXNjaC5kZSIsInJlc3QiOiJ3cC1qc29uIiwic3JjIjoid2ViIiwicmVmIjoiaHR0cHM6XC9cL2xhcnMta3VzY2guZGVcL3dwLWFkbWluXC9hZG1pbi5waHA/cGFnZT1saXRlc3BlZWQtZ2VuZXJhbCJ9)
Is this feature still in development for release?
Kind regards,
Lars Kusch

**Comment by hailite** [comment]
Online services are not available yet. We are preparing the beta testing online servers. After that it would be ready. Will inform in slack channel.
