### ISSUE TITLE
Slack-Link not valid

### ISSUE THREAD

**Issue by LarsK1** [litespeedtech/lscache_wp#197]
Hi there,
unfortunately the slack link in the file [readme.txt](litespeed-cache/readme.txt) is no longer valid: https://join.slack.com/t/golitespeed/shared_invite/enQtMzE5ODgxMTUyNTgzLTNiNWQ1MWZlYmI4YjEzNTM4NjdiODY2YTQ0OWVlMzBlNGZkY2E3Y2E4MjIzNmNmZmU0ZjIyNWM1ZmNmMWRlOTk
Is it possible to create a new one or is this intentional?
Sincerely yours,
Lars Kush

**Comment by hailite** [comment]
https://github.com/litespeedtech/lscache_wp/commit/1cd0573f2db56ef332d80cc4bc53b81d23d70a0d

**Comment by hailite** [comment]
Thanks
