### ISSUE TITLE
Send Optimization Request: Failed to push to LiteSpeed server

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#20]
When pressing the "Send Optimization Request" button on the Image optimization page on a site with 128 different images, the following error is thrown:

> Failed to push to LiteSpeed server: cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received

![captura](https://user-images.githubusercontent.com/802183/32135334-94832a20-bbfd-11e7-9b97-30cb0afd91fe.PNG)

**Comment by hailite** [comment]
That happens when server is busy. Should be fine now.

**Comment by JMCA2** [comment]
Just tried and failed again.
It doesn't happen when testing on another site with fewer images (27 vs 128)

**Comment by hailite** [comment]
May be caused by slow network communication as your site is from LU. Will consider to add more child server close to your location. Thanks.

**Comment by JMCA2** [comment]
Maybe another way to also avoid time-outs could be to send the images in groups/batches? so they are not sent to the server all at once? It would reduce the chances of error and reduce server load.
There are sites (like online stores) that have a few GBs of images for thousands of products.

**Comment by hailite** [comment]
Thats not to send the image file itself to server but only the img basic info, such as src, file md5. Our server will proceed a callback to make sure this request is from your original server. The timeout happened at that time.

**Comment by JMCA2** [comment]
Now when I click "Send Optimization Request" there's a different error: `Failed to push to LiteSpeed server: Previous optimization requests remaining in queue: 14121`

**Comment by hailite** [comment]
Yes thats because the images you pushed still have 14121 left. Before they are optimized, no new image will be accepted.

**Comment by JMCA2** [comment]
But no images seem to have been optimized or requested, this is showing on my dashboard:
![captura](https://user-images.githubusercontent.com/802183/32247754-a5267c64-be83-11e7-852c-db012bc125e0.PNG)

Any ideas?

**Comment by hailite** [comment]
You may need to create a tix or leave your key summary&domain for us to debug.

That check is based on the key you send to server.

**Comment by JMCA2** [comment]
Just sent an email to bug@ to open a ticket with more info regarding this.

Thank you

**Comment by hailite** [comment]
In v1.6.2 IAPI is improved. Please try.

For the unfinished ones, we will add a callback notification to client later. Also the optimization panel will be improved to show more info that synced from server.

**Comment by JMCA2** [comment]
Just got time-out again trying v1.6.2 unfortunately

Good to know about the plans to add callback notification

**Comment by hailite** [comment]
timeout issue is fixed today on server side. Please give it a try. Thanks.
