### ISSUE TITLE
RC7 creates huge server load with cron image optimization

### ISSUE THREAD

**Issue by sintos** [litespeedtech/lscache_wp#203]
I enabled cron image optimization with rc6 and it was working fine continiously for days. After upgrading to rc7, image optimization creates huge server load after some time.
I couldn't identify a pattern when this happens (sometimes few minutes after enabling cron image optimization, sometimes after hours).

**Comment by hailite** [comment]
If you turn debug on, you can check it when the server is under heavy load. See what triggered that.

**Comment by hailite** [comment]
The major fix in rc7  is CCSS cron fix. Might be caused by CCSS generation.
