### ISSUE TITLE
CDN & webp for video poster image

### ISSUE THREAD

**Issue by publicarray** [litespeedtech/lscache_wp#204]
The poster image is not served from a CDN or the webp format: e.g.

```html
<video poster="https://www.example.com/wp-content/uploads/2020/03/poster.png" preload="none" src="https://cdn.example.com/wp-content/uploads/2020/03/video.mp4"></video>
```

**Comment by publicarray** [comment]
Currently background images in CSS are not using the webp image because by adding `background-image: url("image.webp");` before the last `background-image` means it does nothing. Only the last `background-image` statement will be used. Also if a more complex background is used only the url should be modified.

```css
linear-gradient(0deg,rgba(255,255,255,0.6),rgba(255,255,255,0.6)),url(image.jpg)
```

**Comment by hailite** [comment]
Thanks for report.

CDN and webp fixed in https://github.com/litespeedtech/lscache_wp/commit/fd1e8079481588ba57741de0f55a38418c1f1dbf .

Background image in extra CSS file won't replace currently.

**Comment by publicarray** [comment]
Thanks for the quick fix!

That’s understandable. Is there plans to add this in the future?

**Comment by hailite** [comment]
Yes its in todo, but won't be soon.
