### ISSUE TITLE
[Feature request] Option to only cache Home page

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#21]
It would be great to have an setting to only cache the home, and exclude all other pages.

This would be very useful for websites with high-traffic on home page and low traffic on individual pages (for example a low-traffic online store with thousands of different product pages).
In that use case, on most visits the cache has to be regenerated and might take longer to load than with no cache. But still want to benefit from cache on homepage as it is visited by all users

**Comment by hailite** [comment]
You can set `Default Public Cache TTL` to 30s, and keep `Default Front Page TTL` as a long TTL.

When generating cache, it didn't take extra time so you don't need to worry about it.

**Comment by JMCA2** [comment]
So even if it's the first load, it doesn't take longer to load the page (as it needs to write it to cache)?

**Comment by hailite** [comment]
You can ignore that time cost when saving cache I think. From benchmark you can see that's really fast.

**Comment by JMCA2** [comment]
I'll do that then.

Thank you!
