### ISSUE TITLE
v3.0.2 Database issue

### ISSUE THREAD

**Issue by LarsK1** [litespeedtech/lscache_wp#211]
Since the new release the following database-error appears:
`[16-Apr-2020 01:59:15 UTC] WordPress database error Table '*_stbkwordpress.wp_*_3_litespeed_avatar' doesn't exist for query SELECT COUNT(*) FROM 'wp_*_3_litespeed_avatar' WHERE dateline<1586397555 made by do_action_ref_array('litespeed_task_avatar'), WP_Hook->do_action, WP_Hook->apply_filters, LiteSpeed\Avatar::cron, LiteSpeed\Avatar->queue_count` _(replaced database-name through * for security)_. 
Reinstalling the plugin changed nothing?

**Comment by hailite** [comment]
Have you enabled Gavatar localize? Does your WP mysql user have the access to create table?

**Comment by LarsK1** [comment]
No, currently everything is as supposed:
![image](https://user-images.githubusercontent.com/28981528/79754177-6928f600-8317-11ea-8b49-abc4dcda0e95.png)
![image](https://user-images.githubusercontent.com/28981528/79754316-a2f9fc80-8317-11ea-8e91-3f28a535b4ee.png)

**Comment by hailite** [comment]
When you click save, did you see any php/mysql error? Also, have the table created? How about other litespeed_* tables

**Comment by LarsK1** [comment]
No, no errors at all. All other tables seem to work fine. I just noticed it, because of the error.log file

**Comment by hailite** [comment]
Can't reproduce it on our side. Need to debug more. Will reach you on Slack. Thanks.
