### ISSUE TITLE
getting ubuntu@IP: Permission denied (publickey) in intial setup in AWS

### ISSUE THREAD

**Issue by jonrrivera** [litespeedtech/lscache_wp#218]
Hi, 

I am looking to set up this new EC2 instance using lscache Wordpress and I am not able to connect to the server as instructed [here](https://docs.litespeedtech.com/cloud/images/wordpress/#quick-start).

Please lmk if you need more context, thank you!

**Comment by Code-Egg** [comment]
HI @jonrrivera ,

Do you may see any "Select key pair" message after clicking the Launch button from AWS? 
![launch](https://user-images.githubusercontent.com/17311438/80803811-68972780-8b81-11ea-91a7-18bf2bed63f7.png)

If so, when ssh to the liunx server from your windows, you need to add the key first. 
Check https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html for more information. 

You can also use the AWS build-in console to SSH by selecting the instance from AWS > click the **Connect** button > Choose EC2 Instance Connect > Set Username to `ubuntu` > Click the **Connect** button

Best,
Eric

**Comment by jonrrivera** [comment]
@Code-Egg appreciate the reply. I am still getting the error after selecting a key pay and downloading it into my computer. And trying to connect via the EC2 Instance Connect

<img width="1055" alt="Screen Shot 2020-05-01 at 3 32 07 PM" src="https://user-images.githubusercontent.com/18686388/80835653-33122e80-8bc1-11ea-91ac-19580687e619.png">

Not sure where to move over from here... :/

**Comment by Code-Egg** [comment]
Hi. I just launched a new one without any SSH issue. Maybe there was some issues on AWS, please try to launch a new one from different location , e.g. N. Virginia with us-east-1a zone. If you can't even access to the instance via AWS build-in console, then you may want to raise a ticket to AWS support. 
Let us know if different zone works or not.

**Comment by jonrrivera** [comment]
I was only able to change the subnet to the one in the screenshot. not sure where to change the location to n. Virginia. going to give this a run tho.

<img width="884" alt="Screen Shot 2020-05-01 at 4 56 58 PM" src="https://user-images.githubusercontent.com/18686388/80841232-006e3300-8bcd-11ea-88d4-0ccc60d6c91f.png">
