### ISSUE TITLE
.lscache_htaccess_bak.zip publicly readable

### ISSUE THREAD

**Issue by jorisvdz** [litespeedtech/lscache_wp#221]
Hi!

When using the LiteSpeed Cache WordPress-plugin with OpenLiteSpeed server, there are several files created in the root folder of the WordPress install. Some of them are publicly readable, for example ".lscache_htaccess_bak.zip".

In [another thread](https://wordpress.org/support/topic/lscache_htaccess_bak-zip-is-not-protected/) I have read that LSWS should block these files from being publicly readable. However, that not seems the case. Do I need to manually block the files from being publicly readable, or do I have to add some config in LSWS?

Thank you!

**Comment by hailite** [comment]
In v3, we fixed this issue. There is no .zip file created but only a `.htaccess.bk`. Can you give that a try?

Back to the question, yes you should block the access to that file if its public visitable.

**Comment by jorisvdz** [comment]
Hi! Actually I am using version 3. V3.0.8.6 to be precisely...

**Comment by hailite** [comment]
You can delete .lscache_htaccess* files. They are not used anymore.

**Comment by jorisvdz** [comment]
Thanks, I will try to remove the file and let you know if the file is generated again.
