### ISSUE TITLE
[Feature request] Replace original images

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#23]
I think It would be great to have the option to automatically replace original images with the optimized versions.
By default, original images should be kept alongside the optimized ones, but it would be useful to have an optional setting to just replace them when optimizing.

Would help save disk space on budget shared hosting plans with tight quotas

Right now using the image optimization means ~x3 disk usage (original + optimized + webp). With this feature it, it would be reduced to just x2 (optimized + webp)

**Comment by hailite** [comment]
That is true. Noted. Thanks.

**Comment by hailite** [comment]
BTW, it's in our dev plan since https://wordpress.org/support/topic/suggestion-for-image-optimization/#post-9800129

**Comment by JMCA2** [comment]
Good to know, thanks :)

**Comment by hailite** [comment]
Yes that is correct. I have the same feeling personally. 

https://github.com/litespeedtech/lscache_wp/commit/1be24b0526adc2b704278f0cc734465855c943be

Here you are.

**Comment by JMCA2** [comment]
@hailite Good stuff

Would be even better if it was possible to just replace the images instead of deleting them after (so that the host space limit is never reached)

Thanks!

**Comment by hailite** [comment]
Between those two actions there are only couple more images generated I think. Once we make that process automatically, it will be deleted automatically too. Thus I believe you can get you want too.

**Comment by hailite** [comment]
Auto remove backups is added in https://github.com/litespeedtech/lscache_wp/commit/95fe5ef469b2878f05dcacb7264cdc2b23e74c49
