### ISSUE TITLE
PHP 5.3 support broken

### ISSUE THREAD

**Issue by JTS-FIN** [litespeedtech/lscache_wp#230]
This commit has broken PHP 5.3 support:
https://github.com/litespeedtech/lscache_wp/commit/5b8f202edc8e7f3d9d641bd77756b0c013864313

This line does not run with PHP versions < 5.4.0:
`$options[ CURLOPT_RESOLVE ] = [ $url ];`

I confirmed it in here:
https://3v4l.org/ov55d

Using PHP 5.3 the public site works ok, but when trying to log in to Wordpress admin, it gives 500 error:
`[26-May-2020 07:58:12 UTC] PHP Parse error:  syntax error, unexpected '[' in /home/username/public_html/wp-content/plugins/litespeed-cache/src/crawler.cls.php on line 670`

Hope this gets fixed soon, since plugin claims to be 5.3 compatible, but it is now breaking Wordpress installations that use it.

**Comment by hailite** [comment]
https://github.com/litespeedtech/lscache_wp/commit/55961af33e8e419f56f7bddfa302ba33fab71c11

Will be in next release (v3.1.1). Thanks.
