### ISSUE TITLE
need to add a global parameter to select the output format to the cli command 

### ISSUE THREAD

**Issue by alya1992** [litespeedtech/lscache_wp#254]
example: wp litespeed-option all --json

**Comment by alya1992** [comment]
available only in tabular output:
![image](https://user-images.githubusercontent.com/37505269/88026790-0b3ac300-cb3f-11ea-8db8-70c0a667a125.png)

**Comment by hailite** [comment]
Done in https://github.com/litespeedtech/lscache_wp/commit/efdac5338b332dd9b656cd60afebbe7dbb399cc9

**Comment by alya1992** [comment]
@hailite  please tell me when version 3.3 will be released?

**Comment by hailite** [comment]
No ETA yet. You can use `Beta Test` from `Toolbox` menu to install the latest commit version.
