### ISSUE TITLE
3.3 update broken CDN refresh in CSS/JS files

### ISSUE THREAD

**Issue by ribeiroeder** [litespeedtech/lscache_wp#257]
3.3 update
Page Optimize CSS/JS Combine/Minify file versions will be differentiated by query string hash instead of new filename to reduce DB/file system storage.

————–

I use BunnyCDN and after this change in the last update the minified CSS / JS files always keep the same name, making it impossible for me to access the new files as they have already been synchronized on the CDN.

I looked for an option that would keep changing the names for each purge but I couldn’t find it.

**Comment by lucasRolff** [comment]
This can be fixed in BunnyCDN's settings directly:

Go to `Pull Zones` in BunnyCDN, click on the Pull Zone for your site, then Caching -> Vary Cache, and click "URL Query String":

![bunnycdn](https://snaps.hcdn.dk/qneqGkpLPd5Vlcfi86bPQ75CeGFY4mfTp6hvdLIssP.png)

**Comment by ribeiroeder** [comment]
Thanks @lucasRolff !!!

I did the test and it worked, I will adjust the configuration on all my Pull Zones
