### ISSUE TITLE
Improve Admin Headings for Accessibility

### ISSUE THREAD

**Issue by steverep** [litespeedtech/lscache_wp#27]
For good accessibility and proper semantics, please change the top headings in the admin area from an `<h2>` to an `<h1>` (e.g. "LiteSpeed Cache Management" or "LiteSpeed Cache Settings").  Also, please put the version number outside of this tag as it causes extra unnecessary reading to screen readers and is not consistent with the visual appearance.

**Comment by hailite** [comment]
Committed in https://github.com/litespeedtech/lscache_wp/commit/75ca4616f03f47176aa3f24271a159129e7b5cbc

Thanks.
