### ISSUE TITLE
Plugin page notice cannot be hidden

### ISSUE THREAD

**Issue by cliffordp** [litespeedtech/lscache_wp#271]
WordPress v5.5.1
LiteSpeed plugin v3.5.0.2

Clicking "X" to close refreshes the page and the GIANT notice cannot be hidden.

![image](https://user-images.githubusercontent.com/1812179/97033712-63f86e00-1529-11eb-996c-4946e91f0c0c.png)

**Comment by hi-hai** [comment]
This issue is stated in https://wordpress.org/support/topic/intrusive-ad-or-announcement-again-why/

v3.5.1 also fixed that bug.
