### ISSUE TITLE
Announcement is always visible

### ISSUE THREAD

**Issue by Kyzoe** [litespeedtech/lscache_wp#272]
I love Litespeed on our servers, and also the litespeed cachr plugin, but in the latest version the announcement cannot be hidden which is terrible, i don't want a annouuncement in my face every time i visit the plugins page or the LSCP page; Although there is a X to hide it doesn't work.

https://images.kyzoe.be/chrome_wuwwJlB0dE.png

Please correct this

**Comment by hi-hai** [comment]
The message will be dismissible since v3.5.1. There is a bugfix in v3.5.1 for that X button.
