### ISSUE TITLE
Cloudflare domain autocomplete is not working

### ISSUE THREAD

**Issue by mircobabini** [litespeedtech/lscache_wp#290]
RE:
> You can just type part of the domain. Once saved, it will be matched with the current list and completed automatically.

I tried adding few chars and also all chars but the last.

It always autocomplete with the first of the list.

WP 5.6 + LSC 3.6.1

**Comment by usabe** [comment]
Greetings @ mircobabini,

Thank you for your feedback. Not sure if you already have the issue figured out and resolved? Per your reporting, we just did some internal tests with real world setup ( a few real domains for live sites through cloudfare). The function seems working fine. As long as I input the first character of the domain name, Save Changes, then it is updated with the correct match.

If the issue still persists on your side, could you please open a ticket by sending an email to support at litespeedtech.com? We may need to check your specific setup to see why it behaves as you claimed.

Best regards

**Comment by mircobabini** [comment]
I can't reproduce it anymore. Seems like it was a network error maybe. Thanks!
