### ISSUE TITLE
Abuse/Security issue

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#292]
Litespeed cache plugin is grabbing the content of any URL by executing the following URL:

`https://example.com/wp-content/litespeed/localres/closte.com%2F`

Example URL: 
`https://closte.com/wp-content/litespeed/localres/closte.com%2F`

Now imagine, if the URL is 10MB large and I send 10K one by one requests.
Some kind of validation or changing the logic is a must.

**Comment by hi-hai** [comment]
Will give a fix and included in next release.

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/commit/2a8b5244a79929295e1437eb779c637b0d529e38
