### ISSUE TITLE
Feature request: Delay js 

### ISSUE THREAD

**Issue by phamquangbaoplus** [litespeedtech/lscache_wp#305]
For some 3rd party js, 
It should be delay until the user Interactive (mouseover, keydown, touchmove, touchstart)

**Comment by hi-hai** [comment]
Thanks for the suggestion. Yes this is in our todo list, along w/ some other page score enhancements as Pagespeed insight changed their algorithm.

**Comment by styrketrappan** [comment]
Perfect @hi-hai !

**Comment by webhouse-dev** [comment]
Any updates on that @hi-hai ?

**Comment by hi-hai** [comment]
its already done in dev. Latest dev is 3.7rc35.

**Comment by webhouse-dev** [comment]
ty!

**Comment by hi-hai** [comment]
It will be auto loaded if the visitor has any interaction.

**Comment by hi-hai** [comment]
BTW, we are making a Guest Mode. In this new feature, you don't have to delay your JS at all. The page of guest mode will auto maximize the optimization.

**Comment by webhouse-dev** [comment]
sounds good... however still if iframe lazy loading is turned on, youtube embed videos are blank... not loading at all

have a look here - [that post is missing yt video](https://tomrobak.com/blog/jak-sprawdzic-id-wordpress/)

**Comment by webhouse-dev** [comment]
> BTW, we are making a Guest Mode. In this new feature, you don't have to delay your JS at all. The page of guest mode will auto maximize the optimization.

Can't wait to test it!!!

**Comment by webhouse-dev** [comment]
@hi-hai have you seen that [video](https://d.pr/v/OCFqYv) ?

**Comment by phamquangbaoplus** [comment]
> BTW, we are making a Guest Mode. In this new feature, you don't have to delay your JS at all. The page of guest mode will auto maximize the optimization.

So there is no option to delay js myself?

**Comment by hi-hai** [comment]
The option is under JS optm
