### ISSUE TITLE
Not auto-enable if Visual Composer is installed

### ISSUE THREAD

**Issue by josemi-ca** [litespeedtech/lscache_wp#32]
I think the auto-enable feature should check if the WordPress install has any plugin with known-issues installed.

For installation with Visual Composer, it causes problems unless code is manually edited, so the cache plugin shouldn't be automatically enabled for users.

**Comment by hailite** [comment]
Could you tell more about the manually edited code? We will try to improve the compatibility with Visual Composer.

**Comment by JMCA2** [comment]
This edit is required: https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:lscwp:esi_nonce

otherwise, the page editor won't work well so users can't update the pages design.

Visual Composer said months ago that it would add LSCache compatibility, but still nothing..

Thanks

**Comment by hailite** [comment]
We will follow this up.

**Comment by JMCA2** [comment]
Thank you. Please let me know of any news regarding this

**Comment by JMCA2** [comment]
Any updates regarding this?
Would it be possible to make the required changes on lscache-wp side so its not necessary to edit visual composer code with https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:lscwp:esi_nonce?

Thank you

**Comment by hailite** [comment]
The below is from WPBakery Support:

Unfortunately, the cache compatibility has not been checked in recent releases. But, the good news is that the development team is planning to revamp the existing plugin and all the compatibility issues will be checked during it.

Thank you,
