### ISSUE TITLE
Store entries in wp_options as serialized arrays

### ISSUE THREAD

**Issue by binaryfire** [litespeedtech/lscache_wp#324]
Hi guys,

I just took a look at my wp_options table and saw that every LSCache setting is stored as a separate entry. This isn't good for site performance. Large wp_options tables (for example on WooCommerce stores) are a major performance bottleneck in WordPress.

The recommendation is to store as much as possible in serialized arrays (single entries). Would it be possible to make this change to the plugin? The wp_options bloat from LSCache is more than any other WP plugin I've seen. Many of the settings pages could have all their fields stored as a single entry.

Some reference links:
https://kinsta.com/knowledgebase/wp-options-autoloaded-data/
https://websensepro.com/blog/improve-database-performance-by-cleaning-wp-options-table/

**Comment by hi-hai** [comment]
LSCWP's options are limited. This won't be a performance issue if you count your wp_options table's record and compare two counts.

Thanks for the suggestion.

**Comment by binaryfire** [comment]
@hi-hai Helli Hai. Thanks for the reply. I'm not sure what you mean when you say they are limited. There are almost 200 entries added by LSCache to the wp_options table. Please see the attached picture. This really isn't good for site performance:

![lscache options](https://user-images.githubusercontent.com/5361908/115135734-f18cc480-a059-11eb-9aaa-df643bf5b967.png)
