### ISSUE TITLE
Litespeed Cache Beta 4.0 disables all the cron jobs. 

### ISSUE THREAD

**Issue by tp-atlas** [litespeedtech/lscache_wp#340]
How to:
1. Set define( 'DISABLE_WP_CRON', true); to wp-config
2. Set Server Cron Job to every 1 min. 
3. Upgrade to Beta 4.0 LSC. 

Result:
Crons no long runs that is not only LSC cron but all other crons too. 

It seems It is caused by Guest Mode

**Comment by usabe** [comment]
Hello @andrewgc43 

I just answered your same question in the forum. Thank you for your reporting, but we couldn't reproduce this based on your above descriptions. Please verify if it's caused by some other factors.

Best regards,
Abe
