### ISSUE TITLE
How about adding unused CSS remove option, similar to WP-Rocket. 

### ISSUE THREAD

**Issue by Dark-Cod3r** [litespeedtech/lscache_wp#350]
How about adding remove unused CSS option... 
https://github.com/wp-media/wp-rocket/issues/3635

**Comment by mrapino** [comment]
I'd also be interested in this functionality ... similar to what RapidLoad.io does.

**Comment by hi-hai** [comment]
Its already in v4.0, called UCSS. You can use beta test -> dev for it.

**Comment by mrapino** [comment]
> Its already in v4.0, called UCSS. You can use beta test -> dev for it.

Thanks! Do you know when v4.0 will be production ready?

**Comment by Dark-Cod3r** [comment]
> Its already in v4.0, called UCSS. You can use beta test -> dev for it.

So, my  site need to be on Quic CDN to make it work, or if my site is on Cloudflare, UCSS still work..?!

**Comment by qtwrk** [comment]
> > Its already in v4.0, called UCSS. You can use beta test -> dev for it.
> 
> So, my site need to be on Quic CDN to make it work, or if my site is on Cloudflare, UCSS still work..?!

no , UCSS/CCSS and CDN are 2 independent , separated features

**Comment by Dark-Cod3r** [comment]
> > > Its already in v4.0, called UCSS. You can use beta test -> dev for it.
> > 
> > 
> > So, my site need to be on Quic CDN to make it work, or if my site is on Cloudflare, UCSS still work..?!
> 
> no , UCSS/CCSS and CDN are 2 independent , separated features

One more thing. How can i know if its really working.?! cause i enabled it, waited for an error, run a url in Google Pagespeed, but it is still showing unused CSS..!

**Comment by qtwrk** [comment]
you can check the request list , to see how many CSS requests there is

**Comment by Dark-Cod3r** [comment]
> > Its already in v4.0, called UCSS. You can use beta test -> dev for it.
> 
> So, my site need to be on Quic CDN to make it work, or if my site is on Cloudflare, UCSS still work..?!



> you can check the request list , to see how many CSS requests there is

i Checked.. It showing No Requests (No History available)..

**Comment by qtwrk** [comment]
1. make sure you have a valid domain key , you can try refresh it to obtain a new one if needed
2. make sure your server IP setting in QC dashabord is correct, if you have linked it to a QC account 
3. make sure you have enable `CSS combine` and `generate UCSS`
4. go dashboard page on plugin's menu ,  check if you have any queue in Unique CSS ,   you can try manually run it if you don't want to wait for cron to do it 
5. after that , check what is content inside `/wp-content/litespeed/ucss/`

**Comment by Dark-Cod3r** [comment]
> 1. make sure you have a valid domain key , you can try refresh it to obtain a new one if needed
> 2. make sure your server IP setting in QC dashabord is correct, if you have linked it to a QC account
> 3. make sure you have enable `CSS combine` and `generate UCSS`
> 4. go dashboard page on plugin's menu ,  check if you have any queue in Unique CSS ,   you can try manually run it if you don't want to wait for cron to do it
> 5. after that , check what is content inside `/wp-content/litespeed/ucss/`

After enabling CSS combine, it seems to be working now.. CSS combine is must enable option i guess if we going to use UCSS...

**Comment by qtwrk** [comment]
when you see an options in setting menu that start with empty whitespace in front than above one ,  that means above one is the master switch for that options 

like  

```
Other options1
Combine CSS
     Generate Unique CSS
Other options2
...
Load async CSS 
      Generate Critcal CSS
Other options3
Other options3
...
```


so in this exmaple ,  combine is master switch for ucss , and load async css is master switch for ccss

**Comment by Dark-Cod3r** [comment]
> when you see an options in setting menu that start with empty whitespace in front than above one , that means above one is the master switch for that options
> 
> like
> 
> ```
> Other options1
> Combine CSS
>      Generate Unique CSS
> Other options2
> ...
> Load async CSS 
>       Generate Critcal CSS
> Other options3
> Other options3
> ...
> ```
> 
> so in this exmaple , combine is master switch for ucss , and load async css is master switch for ccss

Right, Got it.. Just noticed that..
