### ISSUE TITLE
Issue with public cache and user cookies

### ISSUE THREAD

**Issue by AkramiPro** [litespeedtech/lscache_wp#382]
On store sites on the product page, by clicking on the Add to Cart button, the text changes and it becomes paid now.
The cart is stored in a cookie, so if in the meantime the site administrator purge the cache and the user refreshes the page, a cache in which the add to cart button has changed will be displayed to everyone.
Therefore, you must ignore the cookies that the user sends before creating the cache of the pages.
this is very important for large sites with many realtime users.

**Comment by AkramiPro** [comment]
any response ?

**Comment by AkramiPro** [comment]
??

**Comment by hi-hai** [comment]
Please create a ticket long w/ the steps to reproduce your issue. Issues on github are only to discuss certain code.
