### ISSUE TITLE
amp_is_available was called too early - currently doing the 'litespeed_init' hook

### ISSUE THREAD

**Issue by splaquet** [litespeedtech/lscache_wp#392]
I didn't see this listed in the issues, so wanted to report it.  I had to disable AMP at one point, just to regain control of the WP dashboard.  

`PHP Notice:  amp_is_available was called <strong>incorrectly</strong>. 'amp_is_available()' (or 'amp_is_request()', formerly 'is_amp_endpoint()') was called too early and so it will not work properly. WordPress is currently doing the 'litespeed_init' hook. Calling this function before the 'wp' action means it will not have access to 'WP_Query' and the queried object to determine if it is an AMP response, thus neither the 'amp_skip_post()' filter nor the AMP enabled toggle will be considered. The function was called too early (before the plugins_loaded action) to determine the plugin source. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 2.0.0.) in /public_html/wp-includes/functions.php on line 5535
PHP Stack trace:
PHP   1. {main}() /public_html/index.php:0
PHP   2. require() /public_html/index.php:17
PHP   3. require_once() /public_html/wp-blog-header.php:13
PHP   4. require_once() /public_html/wp-load.php:50
PHP   5. require_once() /public_html/wp-config.php:63
PHP   6. do_action() /public_html/wp-settings.php:556
PHP   7. WP_Hook->do_action() /public_html/wp-includes/plugin.php:470
PHP   8. WP_Hook->apply_filters() /public_html/wp-includes/class-wp-hook.php:327
PHP   9. LiteSpeed\Core->init() /public_html/wp-includes/class-wp-hook.php:303
PHP  10. do_action() /public_html/wp-content/plugins/litespeed-cache/src/core.cls.php:131
PHP  11. WP_Hook->do_action() /public_html/wp-includes/plugin.php:470
PHP  12. WP_Hook->apply_filters() /public_html/wp-includes/class-wp-hook.php:327
PHP  13. LiteSpeed\Thirdparty\AMP::preload() /public_html/wp-includes/class-wp-hook.php:303
PHP  14. LiteSpeed\Thirdparty\AMP::maybe_amp() /public_html/wp-content/plugins/litespeed-cache/thirdparty/amp.cls.php:54
PHP  15. amp_is_request() /public_html/wp-content/plugins/litespeed-cache/thirdparty/amp.cls.php:24
PHP  16. amp_is_available() /public_html/wp-content/plugins/amp/includes/amp-helper-functions.php:766
PHP  17. {closure:/public_html/wp-content/plugins/amp/includes/amp-helper-functions.php:352-425}() /public_html/wp-content/plugins/amp/includes/amp-helper-functions.php:429
PHP  18. _doing_it_wrong() /public_html/wp-content/plugins/amp/includes/amp-helper-functions.php:423
PHP  19. trigger_error() /public_html/wp-includes/functions.php:5535`

**Comment by hi-hai** [comment]
This issue was reported in https://wordpress.org/support/topic/amp-66/ and already fixed. You can use latest dev version.
