### ISSUE TITLE
ESI Nonce problem with EDD

### ISSUE THREAD

**Issue by acf-extended** [litespeedtech/lscache_wp#399]
Hello,

The recent ESI Nonce rules update #366 which added the following rules, made the `edd-gateway` nonce invalid when using PayPal Express gateway:

```
edd-* private
edd_* private
```

I had to comment those rules on my local `esi.nonces.txt` file to make the gateway correctly work again.

Regards.

**Comment by acf-extended** [comment]
Update:

Tried again with the recent LSCWP 4.4 update, this time Stripe & PayPal gateways didn't show up at all, even after an "Empty Entire Cache" flush. Had to comment `edd-* private` & `edd_* private` again.

Using latest EDD/EDD Stripe/EDD PayPal plugins version + CloudFlare APO.

**Comment by hi-hai** [comment]
APO is not compatible w/ LSCWP.

**Comment by acf-extended** [comment]
Hello,

Thanks for the answer!

Well as a feedback, I can tell you that I run it since 10 months now with LiteSpeed Entreprise on production server, without any issue (apart from the recent EDD ESI nonce I mentioned).

My setup include public + private cache, ESI blocks (+ custom ESI menu), EDD/Stripe/PayPal, Software Licensing etc... And performance are amazing.

I'll try to disable CloudFlare APO see if that fix the ESI Nonces issues, but I doubt it since EDD Checkout cache is BYPASSED by CloudFlare APO by default.

Regards.

**Comment by acf-extended** [comment]
Hello,

So I disabled CloudFlare APO and re-enabled `edd-*` & `edd_*` ESI nonces rules, and it didn't fixed the issue.

I noticed that the `admin-ajax.php` query that load the EDD Stripe/PayPal gateway have problems with nonce, as ESI Block are actually printed in plain text instead of being processed. Like that:

```
action: edd_load_gateway
edd_payment_mode: stripe
nonce: <esi:include src='/?lsesi=nonce&_control=private&esi=eyJhY3Rpb24iOiJlZGQtZ2F0ZXdheS1zZWxlY3RlZC1zdHJpcGUiLCJfbHNfc2lsZW5jZSI6dHJ1ZX0%3D&_hash=e11150eee913c2cefbaf5a3ced7b3808' cache-control='private' as-var='1' />
```

This problem definitely came out with the recent LSWP 4.4 update and isn't tied to CloudFlare APO since it's now disabled. Also it appears while being logged-in and as guest.

Do you have any idea where it could come from @hi-hai?

Thanks in advance,

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to tell you that the latest LSCWP 4.4.1 update fixed the issue of ESI Block not being processed in the ajax request described above. It looks it was this line on the changelog:

`ESI Fixed ESI failure on non-cached pages caused by DONOTCACHEPAGE constant.
`

We're now back to the initial problem where the PayPal gateway return "Invalid Nonce" when using native EDD ESI Nonces Blocks. Indeed, CloudFlare APO is disabled.

Regards.

**Comment by usabe** [comment]
Hello @acf-extended 

We checked into this issue today and found out that the problem is caused by the fact that some nonce are designed to get verified on the same page as where this nonce is created. Due to the intrinsic mechanism of ESI logic and process, this verification will fail and so get this "invalid" nonce.

So in such cases we can not include this type of nonce into the ESI nonce list. Or include the general ones for this plugin but exclude the problematic fewer ones. Currently there is no such ESI nonce exclude feature but you can request to Hai about this feature for future.

Best regards,
Abe

**Comment by acf-extended** [comment]
After some discussions with the LiteSpeed tech team, we stumbled upon an ESI logic limitation which doesn't allow nonce creation + validation within the same page request with ESI enabled, which was the case in the `EDD-Recurring` addon.

This kind of operation doesn't have any pratical sense, thus why the bug wasn't spotted before. The solution is to remove the nonce from the ESI nonces rules list. I'll contact EDD team to let know that this nonce verification could be removed in the code, as it is useless.

Thanks for you help!

Regards.
