### ISSUE TITLE
Make WebP img pulling optional

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#40]
There's a setting to enable/disable WebP replacement, but even if it is set to Off the WebP images are still downloaded when optimizing.
This is both a waste of space for users and of CPU resources for you.

Could you please add the option to only request normal images optimization? Just like there's an option to only request WebP.

**Comment by zairwolf** [comment]
This is in dev plan already. Should be in v2.4 branch.

**Comment by JMCA2** [comment]
@zairwolf Awesome! Just curious, is v2.4 expected soon?

**Comment by zairwolf** [comment]
Could be in one month, with significant improvement on image optimization. Page score should be A(99) on `Optimize Images` item with new version.

**Comment by hailite** [comment]
Will be in v2.4 branch. 

Could be in one month, with significant improvement on image optimization. Page score should be A(99) on Optimize Images item with new version.

**Comment by hailite** [comment]
Done in https://github.com/litespeedtech/lscache_wp/commit/3784ed94be733cf7f258e4555d6230ad1da05c41
v2.4 branch can't be tested currently bcos image servers need to update too.
