### ISSUE TITLE
Typos/Bugs Found in GUI

### ISSUE THREAD

**Issue by DaveyJake** [litespeedtech/lscache_wp#41]
Inside the [`gui.class.php`](https://github.com/litespeedtech/lscache_wp/blob/master/litespeed-cache/inc/gui.class.php) file, lines [`342`](https://github.com/litespeedtech/lscache_wp/blob/master/litespeed-cache/inc/gui.class.php#L342) and [`350`](https://github.com/litespeedtech/lscache_wp/blob/master/litespeed-cache/inc/gui.class.php#L350), there's an unnecessary `"` at the tail end of the opening `<span>` tags.

#### Line 342:
`'title' => '<span class="ab-icon" title="' . __( 'LiteSpeed Cache Purge All', 'litespeed-cache' ) . '""></span>',`

#### Line 350:
`'title' => '<span class="ab-icon" title="' . __( 'LiteSpeed Cache', 'litespeed-cache' ) . '""></span>',`

Came across it when working on the back end of a client's site and viewed inside of Chrome DevTools.

**Comment by hailite** [comment]
Thanks.
Fixed in https://github.com/litespeedtech/lscache_wp/commit/d778be96c36bb96b8e6f617e57941df79c642faa
