### ISSUE TITLE
Option to change debug.log location?

### ISSUE THREAD

**Issue by khanh-nt** [litespeedtech/lscache_wp#421]
As the title, currently debug.log is always in /wp-content/debug.log and /wp-content/debug.purge.log
How to change them to another location? Or just simple please make a restrict for them please?

**Comment by lucasRolff** [comment]
LSCWP should simply follow the `WP_DEBUG_LOG` constant from wp-config.php ( https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_log ), which allows defining the path for the debug log.

With that said, WP itself suggests blocking it in `.htaccess` as per https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging - they also give the example code for you to enter into your .htaccess file.

**Comment by khanh-nt** [comment]
Ya, I have define debug.log of wordpress out of VH ROot and dont care about set any rules to deny from unwanted access. But seem lscache still use the original location.

**Comment by khanh-nt** [comment]
And of course we dont want litespeed logs and wordpress logs in the same file.

**Comment by hi-hai** [comment]
@khanh-nt Will a PHP const to define debug path help?

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/commit/9747cff4addff3729be1f5d03d501817d1c5b110
