### ISSUE TITLE
Automatic Disablement of WP Core Lazy Loading

### ISSUE THREAD

**Issue by VR51** [litespeedtech/lscache_wp#440]
I have issues with lazy-loading and the way it affects the display of ads. The problem is caused by over-optimization.

WordPress Core has lazy-loading built into it. This core feature implements lazy-loading for images and iframes. I want to disable WP's native lazy-load feature and use the LS Cache lazy-load feature instead because LS Cache is easier to fine tune or disable it for specific image/iframe classes.

When lazy-loading is enabled in LS Cache, does this automatically disable WP's native lazy-load solution. If the answer is 'no' will a future version of LS Cache automatically disable native lazy-loading or will an option to disable it be added to the LS Cache options screen?

**Comment by hi-hai** [comment]
This makes sense. Done in https://github.com/litespeedtech/lscache_wp/commit/233b5fbef05a2d74613ca9ea595e872f4cf1e8cc.
Thanks.

**Comment by VR51** [comment]
Thank you!
