### ISSUE TITLE
suggested additional default nonce for divi / esi

### ISSUE THREAD

**Issue by rtpHarry** [litespeedtech/lscache_wp#441]
Please excuse the somewhat sloppy nature of this ticket as I am very much out of my depth right now.

I've read the [documentation for the ESI](https://blog.litespeedtech.com/2020/07/08/cache-wordpress-nonces/).

I've been experiencing failures with mailchimp newsletter sign up form widget on a divi powered site with litespeed cache. Cache is set to 1 week and nonce expires after 12 hours from what I understand.

Based on [this code](https://github.com/kennethryerson/Divi/blob/master/functions.php#L3012), which is the submit handler for the newsletter sign up form, and matches the error that I've been receiving, I think that `et_load_nonce` should be added to the list of defaults somewhere?

Looking at the [list of predefined nonces](https://github.com/litespeedtech/lscache_wp/blob/master/data/esi.nonces.txt) I can see its not in there, but there is some mention that divi nonces are predefined elsewhere so I'm not sure the best place.

Can somebody turn this into a pr for the correct spot please?

**Comment by rtpHarry** [comment]
It seems that perhaps the nonce has changed name at some point, as I just found where the divi nonce's are set up and the comment says its for the subscribe module, which is what im experiencing issues with:

  - https://github.com/litespeedtech/lscache_wp/blob/f98b046947b2cf28b1008720e4f4603fdc47359d/thirdparty/divi-theme-builder.cls.php#L38

**Comment by rtpHarry** [comment]
Ok I should have done my thinking inside my head instead of out in public as this snippet is from 8 years ago and looking at the latest version of divi it now uses the `et_frontend_nonce` for that function so I think all I needed to do was enable ESI.

**Comment by lslisa** [comment]
Thinking out loud is ok. Maybe it will help someone else with a similar issue down the line :-)

**Comment by rtpHarry** [comment]
:)
