### ISSUE TITLE
Viewport Image (VPI) did not work.

### ISSUE THREAD

**Issue by mmieszalski** [litespeedtech/lscache_wp#477]
In the previous report I wrote about the indexing robot not working, the problem has been solved in version 5.2, unfortunately there is another problem with Viewport Image (VPI), tasks failing (Requests in queue: 25). Manual execution only refreshes the page.

In Page Optimization it looks as if these tasks are still hanging I enclose the screen

![viewport](https://user-images.githubusercontent.com/66949223/183357227-7a3bf8ce-d0f3-4afb-a18c-ccb2efd9db4a.png)

![viewport1](https://user-images.githubusercontent.com/66949223/183357884-0a3c328d-a38c-4a17-8e4d-93b9f26b27a9.png)
.

**Comment by hi-hai** [comment]
You need to paste the debug log when clicking the `run vpi queue manually` button.
