### ISSUE TITLE
How to put multiple values in an option from WP-CLI?

### ISSUE THREAD

**Issue by xLukii** [litespeedtech/lscache_wp#481]
Hi,

I would like to put more values inside the following command:

`wp litespeed-option set 'optm-dns_prefetch[]' //facebook.com`

For example, add two:
```
//facebook.com
//google.com
```

How could I do it? I have tried in many ways, but it was not possible to save it correctly as an array inside the database.

**Comment by hi-hai** [comment]
```wp litespeed-option set optm-dns_prefetch $'fb.com\ngg.com'```

**Comment by xLukii** [comment]
Excellent! It works perfectly. Thank you very much!

One last question: Is it possible to set several options in the same command? That is, for example:

wp-cli litespeed-option set 'optm-dns_prefetch' 'value' set 'optm-html_min' 'value' set...

**Comment by hi-hai** [comment]
That could mess up options :D So no.

**Comment by xLukii** [comment]
Thank you very much!
