### ISSUE TITLE
[CLI] - Presets

### ISSUE THREAD

**Issue by xLukii** [litespeedtech/lscache_wp#493]
Hi!

The new feature of being able to choose a profile and automatically configure the options according to the profile is excellent.

I wanted to suggest adding "Presets" to the CLI, so it's easier to configure when managing multiple sites at once.

**Comment by hi-hai** [comment]
That is a good idea. Will add. Thx

**Comment by xLukii** [comment]
I have created a pull request with the basic options to use Presets from the CLI: https://github.com/litespeedtech/lscache_wp/pull/495

**Comment by hi-hai** [comment]
Thanks for your contribution. It has been merged.
