### ISSUE TITLE
[Feature request] Remove Query Strings From Static Resources

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#5]
If this feature was included, it would make sites get a better grade at pagespeed/pingdom reports.

It should be very easy to implement with just a few lines, see example code at: https://www.sourcewp.com/remove-query-strings-static-resources/

**Comment by hailite** [comment]
Thanks for your suggestion. We will add this in next week's release v1.2.4

**Comment by hailite** [comment]
fixed in #4f9e8644c40a61c5199887f322cb2ec22411f52f

**Comment by hailite** [comment]
Done in https://github.com/litespeedtech/lscache_wp/commit/4f9e8644c40a61c5199887f322cb2ec22411f52f
