### ISSUE TITLE
Remove duplicate code with re-usable function

### ISSUE THREAD

**Issue by maheshwaghmare** [litespeedtech/lscache_wp#518]
As I see in the code, there are multiple places where the code exists:

```php
defined( 'LSCWP_LOG' ) && Debug2::debug()
```

This should be optimized by adding the condition into the `Debug2::debug()` function itself.

See: 
https://github.com/litespeedtech/lscache_wp/search?q=LSCWP_LOG

**Comment by hi-hai** [comment]
No it shouldn't. Performance concern, and more important thing is, in certain places, it may not be defined yet.
