### ISSUE TITLE
LS Object cache is not compatible with wp_cache_delete definition.

### ISSUE THREAD

**Issue by calvinalkan** [litespeedtech/lscache_wp#548]
The [wp_cache_delete](https://developer.wordpress.org/reference/functions/wp_cache_delete/) function has to return a boolean.

`wp_cache_delete( int|string $key, string $group = '' ): bool`

LS Cache's object cache returns an integer. 

Relevant method:

https://github.com/litespeedtech/lscache_wp/blob/b41455d5f39526998067afd66f03aa63df336103/src/object-cache.cls.php#L512

Which calls the PHPRedis extension `del` method.

Which returns `int|false`, 

https://phpredis.github.io/phpredis/Redis.html#method_del

**Comment by adrien-robert** [comment]
Any update on this?
It seems to be causing me issues with WPGridBuilder facets not rendered on front-end when I have Redis Object Cache enabled inside LiteSpeed Cache plugin.

**Comment by tynanbe** [comment]
https://github.com/litespeedtech/lscache_wp/pull/550

**Comment by 65** [comment]
Would also be keen to see this fixed!

**Comment by wilrevehl** [comment]
Bump. This is impacting our use of a security scanner. Thanks for all you do!

**Comment by hi-hai** [comment]
As this is patched, I will mark it as resolved.

**Comment by 65** [comment]
@calvinalkan  can you confirm this is resolved to your satisfaction?

**Comment by calvinalkan** [comment]
https://github.com/litespeedtech/lscache_wp/blob/ce40aeeeeeae579e0f98d4fe0dbb2f8ad9fb4af5/src/object-cache.cls.php#L525

Yea, looks good
