### ISSUE TITLE
Accept header is ignored

### ISSUE THREAD

**Issue by edent** [litespeedtech/lscache_wp#578]
My WordPress blog serves up HTML content *and* JSON content.  It decides on what to send based on the `Accept` header sent by the browser.

LSCache ignores this and sends the wrong content.

For example:

This returns HTML: 
`curl https://shkspr.mobi/blog/2023/09/this-blog-is-now-on-the-fediverse/`

This *should* get JSON, but receives the cached HTML: 
`curl https://shkspr.mobi/blog/2023/09/this-blog-is-now-on-the-fediverse/ -H "Accept: application/json"`

This busts the cache and *does* get JSON: 
`curl https://shkspr.mobi/blog/2023/09/this-blog-is-now-on-the-fediverse/?a=b -H "Accept: application/json"`

Is it possible to tell LSCache to cache content based on the Accept header? I couldn't find anything in the settings - but there are quite a lot of them 😅

(Re https://github.com/Automattic/wordpress-activitypub/issues/442)

**Comment by qtwrk** [comment]
please try add this to your .htaccess 

```
<IfModule LiteSpeed>
RewriteEngine On
RewriteCond %{HTTP:Accept} application/json [NC]
RewriteRule .* - [E=Cache-Control:vary=%{ENV:LSCACHE_VARY_VALUE}+accept_vary]
</IfModule>
```

and purge all

**Comment by edent** [comment]
I've added that, verified it is seen in the plugin, and purged.  I'm still seeing the same issue.

Toolbox:
![Screenshot of the .htaccess file.](https://github.com/litespeedtech/lscache_wp/assets/837136/97018a79-9a1f-4297-9374-145fad6d972b)

**Comment by qtwrk** [comment]
Oops,  forgot to mention,  add to top of htaccess

**Comment by edent** [comment]
Aha! That fixed it. Thanks. Would it please be possible to add an accept header exclusion to the regular UI?
