### ISSUE TITLE
Feature Request: add support for object cache via APCu or OPCache PHP extensions

### ISSUE THREAD

**Issue by richmilns** [litespeedtech/lscache_wp#582]
In certain circumstances, Redis or Memcached are not an option. It might be nice if there was an option to use APCu or OPCache PHP extensions as the object cache backend?

I've [found an interesting project](https://github.com/elcobvg/wordpress-opcache) that does just this (OPCache) and [one that provides APCu support](https://github.com/l3rady/WordPress-APCu-Object-Cache). I think there are other plugins that add this functionally too ([Docket Cache](https://wordpress.org/plugins/docket-cache/)) - but it would be so nice to have this as part of the LiteSpeed plugin!

Other plugins that do similar (but have lots of other stuff that clutters up WP Admin IMO):
- [APCu Manager](https://perfops.one/apcu-manager/)
- [OPCache Manager](https://perfops.one/opcache-manager/)

**Comment by hi-hai** [comment]
Thanks for the suggestion. That is a good idea. However I don't think we will implement this feature into our cache in a short time. If those plugins can work well, would suggest to use them :)
