### ISSUE TITLE
Deprecated: Creation of dynamic property LiteSpeed\Crawler_Map

### ISSUE THREAD

**Issue by oldrup** [litespeedtech/lscache_wp#586]
Hey! Testing LiteSpeed Cache plugin with WordPress 6.4 RC3 and **PHP 8.2,** and WP_DEBUG spat out this deprecation notice in the crawler settings panel:

`Deprecated: Creation of dynamic property LiteSpeed\Crawler_Map::$_tb_blacklist is deprecated in /home/removed/wp-content/plugins/litespeed-cache/src/crawler-map.cls.php on line 37`

![image](https://github.com/litespeedtech/lscache_wp/assets/17141205/6ca0e800-4b04-40c7-88e1-ccf3d2737536)

Just a deprecation notice; probably something you'd be able to reproduce?

Please let me know if I can provide you with anything helpful for troubleshooting.

**Comment by hi-hai** [comment]
patched in https://github.com/litespeedtech/lscache_wp/commit/c726cd047f5e36f09b62438c2cc746b7d6ea913c
