### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#6]
I see the plugin is available in English, Chinese, Dutch, French, Greek, Japanese and Polish.
Any plans to support Spanish?

It’s the second language with most native speakers worldwide

**Comment by hailite** [comment]
We have been looking for a Spanish translator. Lets chat it here: https://wordpress.org/support/topic/spanish-translation-87/#post-9525551

**Comment by hailite** [comment]
We can add you to our litespeed translation slack group. Do you mind sending an email to info@litespeedtech.com so we can add you. Thanks.

**Comment by JMCA2** [comment]
@hailite Email sent
