### ISSUE TITLE
Additional POST requests to node117/node119 are most likely causing excessive server load

### ISSUE THREAD

**Issue by peter-webbird** [litespeedtech/lscache_wp#602]
The Image Optimisation process sends a POST request to all optimisation servers (node117/node119) upon each successful pull. This is found at the end of the `pull()` function in src/img-optm.cls.php
```php
// Notify IAPI images taken
foreach ($server_list as $server => $img_list) {
    $data = array(
	    'action' => self::CLOUD_ACTION_TAKEN,
	    'list' => $img_list,
	    'server' => $server,
    );
    // TODO: improve this so we do not call once per server, but just once and then filter on the server side
    Cloud::post(Cloud::SVC_IMG_OPTM, $data);
}
````

Prior to my implementation of Parallel Image pulls #581, this code was only triggered after all images were successfully downloaded (ie. optimisation 100% complete) and was only sending for that last set of images. This was obviously a bug, so I moved this inside the `while` loop while refactoring the code, but this seems to have had the unexpected side-effect of significantly increasing server load on the primary Image Optimisation servers (as these requests are sent to the Primary nodes, rather than workers).

I think the best solution is to move this out of the `pull()` function entirely and run a separate cron job (say, hourly) to notify the server of any recently downloaded images. This would combine multiple smaller requests into one larger request, significantly decreasing server load.
I suggest implementing this as a new status before `STATUS_PULLED`, such as `STATUS_PULLED_PENDING`. Images will be marked as `STATUS_PULLED_PENDING` (rather than `STATUS_PULLED`) after being pulled down. Once an hour (or so), a new cron job will fetch all `STATUS_PULLED_PENDING` images, notify the server that they were successfully downloaded (ie. the above POST request) then mark these images as `STATUS_PULLED`.
Alternatively, it might be simpler to just store recently pulled images in a transient?

As a temporary fix, the original bug could simply be reintroduced by moving the offending code (above) back outside of the `while` loop (or commenting it out entirely).

**Comment by peter-webbird** [comment]
As a side-note, because this POST request is only triggered once per parallel pull, increasing the pull rate (ie. the number of pull threads) may, counter-intuitively, reduce load on the servers.

This could be done without pushing a Wordpress plugin update, by having the API temporarily return package `32` (Jumbo Group) in all user's enabled packages.

I can't guarantee that this will work though - the extra load from more parallel image requests may be more than the reduced load from less POST requests.

**Comment by hi-hai** [comment]
Thanks for the detailed analysis. Moving the taken notification part out of loop is a proper way to fix this issue. That will be in a hotfix. We will also check on center server side if there is any possible improvement we can do as well.

**Comment by hi-hai** [comment]
@peter-webbird You mentioned  it was a bug as only send last image row to taken notification prior to your PR.
https://github.com/litespeedtech/lscache_wp/blob/v5.7/src/img-optm.cls.php#L1020C18-L1020C29 As the code here, it appends here and submit in group. Isn’t it?

**Comment by peter-webbird** [comment]
The `while` loop in the `pull` function will timeout in most instances - unless there are only a few images to download. This means that the server will never be notified of most images pulled unless the POST request is run inside the `while` loop (or called separately, as proposed above).

**Comment by hi-hai** [comment]
Since v5.5 we implemented async pulling for images. From our side testing, didn't find timeout anymore. Did you encounter the issue w/ LSWS or other webservers?

**Comment by peter-webbird** [comment]
The process does timeout on our servers (running Litespeed).

I assumed that this was by design. The CRON process spawns a PHP process, which runs in a loop until timeout, then a new one starts on the next CRON run. We increased our PHP timeout to 600 (10 minutes) to get the most loops in until timeout, but they will eventually timeout and a new PHP process will spawn.

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/blob/master/src/htaccess.cls.php#L510
Here we added a noabort, which will keep PHP process running w/o timeout until done if using LSWS.
Can you check if your .htaccess has this rule or not? Thanks.

**Comment by peter-webbird** [comment]
I have just checked a few websites across a few different servers. I am not seeing either 'noabort' or 'action=async_litespeed' in the .htaccess files. Other Litespeed rules are present though.
Either way, I can't see this working as intended for websites with thousands of images. Take, for example, a website with 50,000 media items. This is likely to take over a week (potentially even a month) to complete the optimisation for all images. Do you expect this singular PHP process to continue running for that entire week/month without issue?

**Comment by peter-webbird** [comment]
For reference, the relevant .htaccess file from a recently launched website is below:
```
# BEGIN LSCACHE
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
<IfModule LiteSpeed>
RewriteEngine on
CacheLookup on
RewriteRule .* - [E=Cache-Control:no-autoflush]
RewriteRule \.litespeed_conf\.dat - [F,L]

### marker CACHE RESOURCE start ###
RewriteRule wp-content/.*/[^/]*(responsive|css|js|dynamic|loader|fonts)\.php - [E=cache-control:max-age=3600]
### marker CACHE RESOURCE end ###

### marker FAVICON start ###
RewriteRule favicon\.ico$ - [E=cache-control:max-age=86400]
### marker FAVICON end ###

### marker WEBP start ###
RewriteCond %{HTTP_ACCEPT} "image/webp"
RewriteRule .* - [E=Cache-Control:vary=%{ENV:LSCACHE_VARY_VALUE}+webp]
RewriteCond %{HTTP_USER_AGENT} iPhone.*Version/(\d{2}).*Safari
RewriteCond %1 >13
RewriteRule .* - [E=Cache-Control:vary=%{ENV:LSCACHE_VARY_VALUE}+webp]
### marker WEBP end ###

### marker DROPQS start ###
CacheKeyModify -qs:fbclid
CacheKeyModify -qs:gclid
CacheKeyModify -qs:utm*
CacheKeyModify -qs:_ga
### marker DROPQS end ###

</IfModule>
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
# END LSCACHE
# BEGIN NON_LSCACHE
## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
### marker BROWSER CACHE start ###
<IfModule mod_expires.c>
ExpiresActive on
ExpiresByType application/pdf A31557600
ExpiresByType image/x-icon A31557600
ExpiresByType image/vnd.microsoft.icon A31557600
ExpiresByType image/svg+xml A31557600

ExpiresByType image/jpg A31557600
ExpiresByType image/jpeg A31557600
ExpiresByType image/png A31557600
ExpiresByType image/gif A31557600
ExpiresByType image/webp A31557600

ExpiresByType video/ogg A31557600
ExpiresByType audio/ogg A31557600
ExpiresByType video/mp4 A31557600
ExpiresByType video/webm A31557600

ExpiresByType text/css A31557600
ExpiresByType text/javascript A31557600
ExpiresByType application/javascript A31557600
ExpiresByType application/x-javascript A31557600

ExpiresByType application/x-font-ttf A31557600
ExpiresByType application/x-font-woff A31557600
ExpiresByType application/font-woff A31557600
ExpiresByType application/font-woff2 A31557600
ExpiresByType application/vnd.ms-fontobject A31557600
ExpiresByType font/ttf A31557600
ExpiresByType font/otf A31557600
ExpiresByType font/woff A31557600
ExpiresByType font/woff2 A31557600

</IfModule>
### marker BROWSER CACHE end ###

## LITESPEED WP CACHE PLUGIN - Do not edit the contents of this block! ##
# END NON_LSCACHE
```

This was deployed using the attached settings.
[LSCWP_cfg-defaults.data.txt](https://github.com/litespeedtech/lscache_wp/files/13709347/LSCWP_cfg-defaults.data.txt)

**Comment by hi-hai** [comment]
The above site didn't enable crawler. I think that is why.

**Comment by peter-webbird** [comment]
> The above site didn't enable crawler. I think that is why.

Relying on the crawler - which is not enabled by default - is obviously not a reliable solution. I think it is very likely that a majority of users have the crawler disabled. This means that a significant number of requests will be timing out and the server not being notified of images downloaded.

A solution that is simpler to implement might be to simply count the number of downloaded images in the `while` loop and send a POST request when it reaches a certain threshold.

This could look something like this:
```
const NOTIFY_THRESHOLD = 20; // Notify server once this many images have been downloaded

public function pull($manual = false)
{
	...

	$total_pulled_ori = 0;
	$total_pulled_webp = 0;
	$total_pending = 0;

	$server_list = array();
	
	while ($img_rows = $wpdb->get_results($_q)) {
		...

		$complete_action = function ($response, $req_count) use ($imgs_by_req, $rm_ori_bkup, &$total_pulled_ori, &$total_pulled_webp, &total_pending, &$server_list) {
			...
			$total_pulled_ori++;
			$total_pending++;
		};
		...
		// Notify server of images pulled when past threshold
		if( $total_pending > self::NOTIFY_THRESHOLD ){
			foreach ($server_list as $server => $img_list) {
				$data = array(
					'action'	=> self::CLOUD_ACTION_TAKEN,
					'list' 		=> $img_list,
					'server'	=> $server,
				);
				// TODO: improve this so we do not call once per server, but just once and then filter on the server side
				Cloud::post(Cloud::SVC_IMG_OPTM, $data);
			}
			$total_pending = 0; // Reset count
			$server_list = array(); // Reset server list
		}
	}

	// Notify IAPI images taken
	foreach ($server_list as $server => $img_list) {
		$data = array(
			'action'	=> self::CLOUD_ACTION_TAKEN,
			'list' 		=> $img_list,
			'server'	=> $server,
		);
		// TODO: improve this so we do not call once per server, but just once and then filter on the server side
		Cloud::post(Cloud::SVC_IMG_OPTM, $data);
	}
	...
}
```

**Comment by hi-hai** [comment]
What if we add a settimelimit in loop? That will keep extending the execution to avoid timeout.

**Comment by peter-webbird** [comment]
`set_time_limit` is disabled on most servers for security reasons. Unfortunately I don't know of any way to reliably extend a request indefinitely. You should assume that some requests will always timeout and work around that limitation.

**Comment by hi-hai** [comment]
True, in this way not many ways to extend the request. I will give a patch to early return if the pull process will encounter the timeout soon (e.g. 30s left)

**Comment by hi-hai** [comment]
Oh 

> I have just checked a few websites across a few different servers. I am not seeing either 'noabort' or 'action=async_litespeed' in the .htaccess files. Other Litespeed rules are present though. Either way, I can't see this working as intended for websites with thousands of images. Take, for example, a website with 50,000 media items. This is likely to take over a week (potentially even a month) to complete the optimisation for all images. Do you expect this singular PHP process to continue running for that entire week/month without issue?

Can you manually add this section and see if it works or not?
```
RewriteCond %{REQUEST_URI} /wp-admin/admin-ajax\.php
RewriteCond %{QUERY_STRING} action=async_litespeed
RewriteRule .* - [E=noabort:1]
```

I think this is an ideal and preferred solution for timeout. If this can resolve this issue, we can add this rule to be default one, regardless of crawler being on or off.

Sorry for misunderstood your answer. I happened to be working on crawler ATM and thought you were using that async call. So didn't get what you meant by 'crawler is off'.

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/commit/9dc1ca21e7765da0728f1f3b62041c5b7bd5a4ea
