### ISSUE TITLE
PHP Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by dcx15** [litespeedtech/lscache_wp#617]
`PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /plugins/litespeed-cache/src/control.cls.php on line 547`

**Comment by hi-hai** [comment]
Patched in https://github.com/litespeedtech/lscache_wp/commit/24f321791f32ddf7a2b8d4c61e7d2b48f7dda7d2
