### ISSUE TITLE
Nonce for WP Data Access plugin

### ISSUE THREAD

**Issue by jure123** [litespeedtech/lscache_wp#643]
Can you please consider adding `wpda-*` nonce pattern into data/esi.nonces.txt, which is used by WP Data Access plugin (https://wordpress.org/plugins/wp-data-access/).

I am not developer of that plugin but we are having a issue using the plugin with LSCache enabled (we receive "token expired" error when the plugin calls admin-ajax.php). I have inspected the plugin code and found that it uses `wp_create_nonce()` with many different nonce starting with `wpda-`, like the following example that add nonce 

```
$nonce_seed = 'wpda-publication-' . $table_name . '-' . $column_names_value;
return wp_create_nonce( $nonce_seed );
```

I'm not experience in LSCache issues like that, but you might know if the above example is a case for adding nonce to esi.nonces.txt.

**Comment by timotei-litespeed** [comment]
Hello

Were you able to fix the issue? 
I suggest to add  `wpda-` in this area
![image](https://github.com/litespeedtech/lscache_wp/assets/162806658/b2852fde-abce-4303-87b3-33c127a17a7d) test the fix and tell us if this works.

**Comment by timotei-litespeed** [comment]
Try adding your nonce to the ESI nonces?
OK, please keep me updated with your results

**Comment by jure123** [comment]
Hi, since I've put `wpda-*` into ESI nonces list our issue is gone. You can probably add it to esi.nonces.txt

**Comment by timotei-litespeed** [comment]
@jure123 
Nice! Added the nonce, will be added in any future releases.
