### ISSUE TITLE
[Feature request] Defer blocking CSS/JS

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#7]
I think it is the main WPO missing from the plugin, to achieve great pagespeed scores with an all-in-one solution

https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery
https://developers.google.com/speed/docs/insights/BlockingJS

**Comment by hailite** [comment]
done in e65d9070bb186ad9d3b884ffaef71b28f60fb5ca
