### ISSUE TITLE
Incorrect Autoloaded Options details

### ISSUE THREAD

**Issue by mukeshpanchal27** [litespeedtech/lscache_wp#717]
## Bug Description
In WordPress 6.6, a new site health check was introduced called [Audit Autoloaded Options](https://core.trac.wordpress.org/changeset/58332).

Recently, a user reported an issue with the autoloaded site health check [#61764](https://core.trac.wordpress.org/ticket/61764). The site health check indicated a problem even though the autoloaded options did not hit the thresholds. You can use the `add_filter( 'site_status_autoloaded_options_size_limit', '__return_zero' );` filter to set the threshold to zero so you can check the Site Health report at `Admin Panel > Tools > Site Health`.

I spun up a demo site, and here are the results:
- **Site Health Check:**
  - Autoloaded Options: 353
  - Size: 40 KB
- **LiteSpeed Plugin:**
  - Autoloaded Options: 112
  - Size: 16.56 KB

The issue is in [this section of the LiteSpeed plugin code](https://github.com/litespeedtech/lscache_wp/blob/master/src/db-optm.cls.php#L308-L319), where it only uses `autoload = 'yes'` in their query, not accounting for `on`, `auto-on`, or `auto` as [wp_load_alloptions](https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/option.php#L582-L643) does, which misleads users.

## Screenshots:
_Note: The first screenshot was taken after the [Performance Lab](https://wordpress.org/plugins/performance-lab/) plugin was installed._

**Site Health Check:**
![Autoload health check](https://github.com/user-attachments/assets/97cc9d20-d401-47c7-9985-46faf8f62fe9)

**LiteSpeed Plugin:**
![LiteSpeed Cache plugin](https://github.com/user-attachments/assets/f075dad9-0cf3-4c5f-b49d-8e040d350691)

**Comment by timotei-litespeed** [comment]
@mukeshpanchal27 thank you for the issue
We have read your suggestion and we are talking of what changes we will do

**Comment by hi-hai** [comment]
This will need some more time for me to further review and check. Will include in next 2nd release as v6.5 is packed and tested. Can't merge this one there. FYI
