### ISSUE TITLE
CookieInformation + LiteSpeed Cache 6.3> SyntaxError: Identifier 'i' has already been declared

### ISSUE THREAD

**Issue by Mgrmjp** [litespeedtech/lscache_wp#721]
Hello,

Updating from LiteSpeed Cache 6.2.0.1 to 6.3 seems to be causing https://cookieinformation.com/ banner script to error and cause it to not work on some sites.

Checking similar sites that are still on 6.2.0.1 seem to be working without fail and issues. Disabling 6.3 LiteSpeed Cache plugin in WordPress completely gets rid of the issue.

The error in question:

`SyntaxError: Identifier 'i' has already been declared`

I was unable to find what change might be causing this looking at the codebase, but does someone have any idea?

One site had "Minify JS" enabled, but disabling that on 6.3 did not have any effect.

Thank you for your time! ⭐

**Comment by szepeviktor** [comment]
> Updating from LiteSpeed Cache 6.2.0.1 to 6.3

This is the changeset
https://github.com/litespeedtech/lscache_wp/compare/b18d2eb2502cac6edfe51ea080d6c6eb346fb57b...a743949

It must be https://github.com/litespeedtech/lscache_wp/blob/master/assets/js/instant_click.min.js
being the only JavaScript.

**Comment by szepeviktor** [comment]
.. previously it was minified but variable names were not changed - for example to `i`

**Comment by hi-hai** [comment]
This has been fixed in latest v6.4-rc1. You can use `dev` to test it from `Beta Test`. It will be released tmr. Please let us know if it fixed ur issue or not. Thx.

**Comment by timotei-litespeed** [comment]
@Mgrmjp was the issue fixed?

**Comment by Mgrmjp** [comment]
> @Mgrmjp was the issue fixed?

Yes the issue is fixed by 6.4 and up. 😊

**Comment by timotei-litespeed** [comment]
I will mark it as resolved :)

**Comment by timotei-litespeed** [comment]
@Mgrmjp is the problem fixed? please mark the issue as resolved if everything is ok
