### ISSUE TITLE
Google Fonts broken with the Async option

### ISSUE THREAD

**Issue by hivepress** [litespeedtech/lscache_wp#787]
There was a commit from November https://github.com/litespeedtech/lscache_wp/commit/5fa335c20ea0ea87d842355f4232272a683f17c3 which removed quotes from a list of Google Fonts here https://github.com/litespeedtech/lscache_wp/blob/431139fb4eb0ddc0b9d4c57ec699bcb3959f8190/src/optimize.cls.php#L604 

As a result, any website with Async option enabled for Google Fonts have broken fonts if there's more than 1 font loaded, because the JS array `["font1","font2"]` becomes `["font1,font2"]`.

I hope this will be fixed in the next update - based on WordPress.org support, this affected many websites.

Thanks!

**Comment by timotei-litespeed** [comment]
@hivepress 
Thank you for the code, we will discuss it.

**Comment by hi-hai** [comment]
Good catch. It will be fixed in next week's v6.5.4 release. Thanks @hivepress

**Comment by hivepress** [comment]
Thanks, appreciate this!

On a side note, I noticed that "display=swap" is added only to the latest font in the list if there's more than 1 font (when the Swap option for Google Fonts is enabled in Page Optimization/CSS). It seems that this option affects only the latest font.

**Comment by timotei-litespeed** [comment]
@hivepress I tested with latest version(6.5.4) which fixes the first issue.
It adds to display last font, but at the end will have effect on all.

See [https://fonts.litespeedtech.ro/](https://fonts.litespeedtech.ro/) 
**Google Async is ON** and **Display is set to swap**
Link generated is: [https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300%7CPT+Sans:400,700%7CPT+Sans+Narrow:400%7CMontserrat:600&display=swap](https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300%7CPT+Sans:400,700%7CPT+Sans+Narrow:400%7CMontserrat:600&display=swap) and it applies the **display: swap** to all font.

For what I see it has the desired effect

**Comment by timotei-litespeed** [comment]
The new version can be tested by going into LSC => Toobox => Beta Test => Click on **master**  => then on "Upgrade"

**Comment by hi-hai** [comment]
@hivepress We didn't change that part in v6.5.4. I was like that, appending display option to the last font to make it work.

**Comment by hivepress** [comment]
Yes I'm aware that there were no changes regarding the display=swap, just wanted to ensure that it affects all the fonts because I noticed that it's added to the last one only. All sorted & thanks for the quick async fonts fix!

**Comment by timotei-litespeed** [comment]
@hivepress You are welcome! and thank you for your help!

**Comment by hi-hai** [comment]
Great. Lets bring this release to be a Christmas gift to all users. Thanks everybody. Happy New Year!
