### ISSUE TITLE
Heave memory usage in Minifier.php

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#8]
We have used many minification plugins but none were throwing out of memory errors.

`PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 18874368 bytes) in /wp-content/mu-plugins/litespeed-cache/lib/vendor/tubalmartin/cssmin/src/Minifier.php on line 286`

`PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 39845992 bytes) in /wp-content/mu-plugins/litespeed-cache/lib/vendor/tubalmartin/cssmin/src/Minifier.php on line 515`

Just after we try your code, we tried **Autoptimize** and **Merge + Minify + Refresh**, both did the job without memory errors.

**Comment by hailite** [comment]
Autoptimize is using the old 2.x minify lib, our minify lib is 3.0.

Can you create a ticket so we can have a further check? Not sure if you have any other options on.

You can email to bug@litespeedtech.com to create a tix.

**Comment by closte** [comment]
I`ll try to reproduce the issue on other site and create a staging site for the test.
One more very important thing that no other plugin has it:
The maximum size of combined CSS/js. You already know that server and Litespeed have a max size for gzip file. Any medium to the large website is getting larger than 1MB combined file size. If you can make internal logic to split into groups e.g 2x files 500KB instead of one 1MB, that will be perfect!

What do you think?

**Comment by hailite** [comment]
That is a good idea. However, how to split it? You know we can't split JS roughly, that may break it.

**Comment by closte** [comment]
Not like pure javascript splitting but calculate usage before adding to the group.

Something like:

Max = 1MB
Current = 0

if((file_to_be_added + Current) > Max){
//create new group
}else{
//add to current group
}

Something similar "fast velocity minify" plugin is doing but for other purposes.
http://prntscr.com/gqy1xg

**Comment by hailite** [comment]
Great. Will add this in schedule.

**Comment by closte** [comment]
While we are here, let me tell you one more feature that no other plugin has it.

Allow specifying custom CSS/JS as well images for HTTP2 server-push. Server-push is not designed to speed up everything and compared to CDN is useless. There is no client-side cache control as well browsers need time to process the push requests.

Check https://closte.com/blog/http-2-server-push-for-wordpress-speed-up-or-slow-down
I didn`t make some hard real-life testing, but CloudFlare confirms the same.

So:
Give the ability to specify CSS/JS and images for server-push. Those CSS and JS files should be excluded in your minify/combine groups.

I think it can work like this.

*******************************
Oh, one more. I saw someone opened a ticket for "Remove query string" for static resources. People just want to get +5 points in those online tests but in real-world actually, they can just have problems.

Nowadays, CDN can be even free, using something like CloudFlare. When assets are cached on CDN but we update WP or some plugin, the site still loads the same JS and can cause errors.
So:
1. Create some unique key, maybe hash calculation on file paths including ver= query string + WP version. Then you can have URL like /min/key.js. Once client updates something, actually Litespeed purge the HTML caches and they load new URL.

*******************************
I didn`t tested LS minification, i`m just givving me suggestions.

**Comment by hailite** [comment]
Fixed in 8c2c3f0780ac3e0f9b019df9b810b59f6edc56f9
