### ISSUE TITLE
[Bug] Query string not removed from wp-emoji-release.js

### ISSUE THREAD

**Issue by JMCA2** [litespeedtech/lscache_wp#9]
The remove query strings from static resources feature is not working for the wp-emoji-release.js file

`/wp-includes/js/wp-emoji-release.min.js?ver=4.8.2`

**Comment by hailite** [comment]
noted

**Comment by hailite** [comment]
We added an option to remove loading WP's emoji which will make visitor's local browser emoji work. Will this work for you?

**Comment by JMCA2** [comment]
Great idea to reduce page size

I still think the query string should be removed from the wp-emoji-release.min.js file, though.
There are people who might want to keep WP emoji, and they expect the `?ver=` to be removed if they have enabled the remove static query string feature

**Comment by hailite** [comment]
fixed in ca1efe2ac07eb93fd4c1d7d47378ea397fb8073e

**Comment by JMCA2** [comment]
Great. Thank you!
